### ISSUE TITLE
Jump to sparse tree

### ISSUE THREAD

**Issue by TLINDEN** [alphapapa/outshine#1]
Hi,

I'm using the following code for a longer time now and I just love it to navigate my emacs config this way. Basically it opens a prompt (with completion) where you can search for a heading. On a match you will jump to that heading, which will be shown as a kind of sparse tree, that is, all other headings outside of it will be collapsed.

Currently it parses headings with regexps, so it only works with elisp files, this needs to be changed so that it works with all kinds of outshine buffers, but I don't know how. Also some code might be redundant and already existent in outshine.el.

If you think this would be worth including into outshine: feel free to do so (I don't care about licensing, from my point of view its public domain). Or, if such a feature already exists, it would be great if you could show me how to use it. Thanks!

Here's the code:

```elisp
(make-variable-buffer-local 'tvd-headings)

(defun tvd/alist-keys (A)
  "return a list of keys of alist A"
  (let ((K ()))
    (dolist (e A)
            (push (car e) K))
    K))

(defun tvd/get-line ()
  "return current line in current buffer"
  (buffer-substring-no-properties
   (line-beginning-position)
   (line-end-position)))

(defun tvd/starts-with (s begins)
  "Return non-nil if string S starts with BEGINS."
  (cond ((>= (length s) (length begins))
         (string-equal (substring s 0 (length begins)) begins))
        (t nil)))

(defun tvd/outshine-is-heading-p (&optional line)
  "return t if current line or LINE is a heading"
  (tvd/starts-with (or line (tvd/get-line)) ";; *"))

(defun tvd/outshine-get-level (heading)
  "return level of HEADING as number, or nil"
  (if (string-match ";; \\(*+\\)" heading)
      (length (match-string 1 heading))))

(defun tvd/outshine-cl-heading (heading)
  "clean HEADING"
  (replace-regexp-in-string ";; \\*+ " "" heading))

(defun tvd/outshine-parse-headings ()
  "extract outshine headings of current buffer"
  (interactive)
  (let ((line nil))
    (save-excursion
      (setq tvd-headings ())
      (beginning-of-buffer)
      (while (not (eobp))
        (setq line (tvd/get-line))
        (when (tvd/outshine-is-heading-p line)
          (add-to-list 'tvd-headings (cons (tvd/outshine-cl-heading line) (point))))
        (forward-line)))))

(defun tvd/outshine-sparse-tree ()
  "expand outline tree from current position as sparse tree"
  (interactive)
  (let ((done nil)
        (pos (point))
        (tree (list (list (point) 5)))
        (l 0))
    (while (not done)
      (outline-up-heading 1)
      (setq l (tvd/outshine-get-level (tvd/get-line)))
      (add-to-list 'tree (list (point) l))
      (when (eq l 1)
        (setq done t))
      )
    (outline-hide-other)
    (dolist (pos tree)
      (goto-char (car pos))
      (outline-cycle))))

(defun tvd/outshine-jump ()
  "jump to an outshine heading with IDO prompt,
update heading list if neccessary."
  (interactive)
  (let ((heading nil))
    (when (or (not tvd-headings)
              (buffer-modified-p))
      (tvd/outshine-parse-headings))
    (if (not tvd-headings)
        (message "Current buffer doesn't contain any outshine headings!")
      (setq heading (if (fboundp 'ido-completing-read)
                        (ido-completing-read "Jump to heading: " (tvd/alist-keys tvd-headings))
                      (completing-read "Jump to heading: " tvd-headings)))
      (when heading
        (show-all)
        (goto-char (cdr (assoc heading tvd-headings)))
        (tvd/outshine-sparse-tree)))))

(eval-after-load "outline"
  '(progn
     (add-hook 'outline-minor-mode-hook
               (lambda ()
                 (local-set-key (kbd "C-c C-j")  'tvd/outshine-jump)))))
```

**Comment by alphapapa** [comment]
Hi there,

Thanks a lot for sharing this, this looks very interesting!  I will take a look at it in more detail sometime soonish.  ;)

My first thought is, have you seen `navi-mode`?  I think that you could use it to get the tree.  Also, have you seen `helm-navi`?  Without having looked at your code in depth, my feeling is that you could get this functionality fairly simply by, e.g. using `helm-navi` to select a heading, then collapse all sections, then expand the selected heading.

I think this is definitely a feature worth having.  My question then is, which package does it belong in?  `outshine`, `navi-mode`, or `helm-navi`?  `outshine`, `outorg`, and `navi` are somewhat interdependent.  In the long term it might make sense to refactor them (or `outshine` and `navi`, at least).

**Comment by TLINDEN** [comment]
Hi,

> have you seen navi-mode?

No, but I took a look at it after your hint. I don't like it though, I don't like to leave my `.emacs` buffer.

> have you seen helm-navi?

Nope, and I won't cause I use IDO only.


best regards,
Tom

**Comment by alphapapa** [comment]
Ok, well, this kind of functionality probably belongs in one of those two packages.  I don't plan on adding navigation like this functionality to Outshine when it already exists in those packages.  Thanks.
