### ISSUE TITLE
Outshine breaks org-cycle with heading structure starting below level 1

### ISSUE THREAD

**Issue by thblt** [alphapapa/outshine#15]
Hi,

If outshine is just `(require)`d, `org-cycle` breaks  with heading structures starting below level 1 (eg, a chapter before a part):

![2018-06-24-114858_3840x2160_scrot](https://user-images.githubusercontent.com/2453136/41817912-9d21e7e4-77a4-11e8-8c23-e862f08dcf7d.png)

Left shows the bug, right is expected behavior (init has `;; (require 'outshine)` commented out).  The structure doesn't fold below the first h1 header, and no amount of `C-u TAB` can get it to fold. 

# Steps to reproduce

From emacs -q, eval the following (adjust paths as needed on lines 1-3) 

``` emacs lisp
(add-to-list 'load-path (expand-file-name "lib/org/lisp" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "lib/outshine" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "lib/outorg" user-emacs-directory))
(require 'org)
(require 'outshine)
```

Visit a org-file with the following contents or a similar structure.

``` org-mode
** Acknowledgments

** Preface

* Part I: structure

This is not folded!!!

** Chapter 1:

Neither is this!!!

** Chapter 2:

And so on

* Part II:

** Chapter 3:

** Chapter 4:
```

the bug disappears if `(require 'outshine)` is commented out.

# Versions

 - Emacs 26.1 on NixOS
 - org-mode release_9.1.13-832-g1bdee3523
 - outorg v2.0-47-g78b0695
 - outshine v2.0-57-g5f1a6b7

Thanks!

**Comment by alphapapa** [comment]
Hi,

Thanks for reporting.  This will probably require some digging to fix.  I think it points to a deeper problem in that simply `require`ing the package shouldn't affect behavior like that, and fixing that may require deeper changes that aren't very feasible for me to make (I'm not the original author, of course).  It's also a bit of an unusual edge case.  ;)

I will "assign" the issue to myself but I don't know when I'll have time to investigate.  If you figure anything out, patches welcome, of course.  :)

Thanks.

**Comment by thblt** [comment]
I isolated the bug in an override of a function from outline.el, PR #16 just deletes the override and seems to work.  PR#17 is more aggressive and deletes all the `outline-` symbols. I haven't tested it, so it deserves some serious testing before being merged, but I think it should be too --- namespace collisions make horrible bugs :)

Thanks!

**Comment by alphapapa** [comment]
Thanks!
