### ISSUE TITLE
(require 'outshine) is effectful

### ISSUE THREAD

**Issue by thblt** [alphapapa/outshine#18]
Browsing through outshine.el, I noticed that just loading the package is effectful[1] --- there are `(put)`s and `(defadvice)`s at toplevel, among other things.  IMHO, it would be better, at least for debugging, if loading had no effects beyond defining new symbols.  

[1] I'd agree that "effectful" in elisp is hard to define, but here it should be understood as doing anything that isn't `def*`  (defun, defvar, defcustom, defmacro...)

**Comment by alphapapa** [comment]
Yes, you're right.  There should be a minor mode that enables and disables Outshine's effects.  Simply `require`ing it shouldn't interfere with any existing code.  It would be nice if this could be done without too much refactoring, but I don't know--it's a large package.  :)

**Comment by thblt** [comment]
For reference, here's a complete list of top-level function in `outshine.el` with where I think they should be: stay at toplevel, or be moved to minor-mode initialization.  From what I see, there's nothing crazy and transition shouldn't be too hard.  

| Function                            | Expected location |
| ----------------------------------- | ----------------- |
| `declare-function`                  | Toplevel          |
| `defadvice`                         | **Minor mode**      |
| `defconst`                          | Toplevel          |
| `defcustom`                         | Toplevel          |
| `defface`                           | Toplevel          |
| `defgroup`                          | Toplevel          |
| `define-key`                        | **Minor mode** [3]      |
| `defmacro`                          | Toplevel          |
| `defsubst`                          | Toplevel          |
| `defun`                             | Toplevel          |
| `defvar`                            | Toplevel          |
| `easy-menu-define`                  | **Minor mode**      |
| `eval-when-compile`                 | Toplevel [1]      |
| `make-variable-buffer-local`        | Toplevel [2]      |
| `outshine-define-key-with-fallback` | **Minor mode**[3]      |
| `outshine-remap`                    | **Minor mode**      |
| `provide`                           | Toplevel          |
| `put`                               | **Minor mode** [4]  |
| `require`                           | Toplevel          |
| `run-hooks`                         | **Minor mode**      |
| `with-eval-after-load`              | **Minor mode**??? [5] |

 1. is just for requiring `cl` only at bytecompile-time.
 2. can probably be removed by using `defvar-local` instead of plain `defvar`
 3. `define-key` and `outshine-define-key-with-fallback` are both used to define keys in `outline-minor-mode-map`, which shouldn't happen.  Calls to these functions should remain at toplevel, but should modify an `outshine-minor-mode-map` and don't touch outline.
 3. Nothing too crazy here:

     ``` elisp
     (put 'outshine-compatible-face 'lisp-indent-function 1)
     (put 'outshine-self-insert-command 'delete-selection
     (put 'outshine-self-insert-command 'company-begin t)
     (put 'outshine-insert-heading :advertised-binding [M-ret])
     (put 'outshine-outline-cycle :advertised-binding [?\t])
     (put 'outshine-cycle-buffer :advertised-binding [backtab])
     (put 'outline-promote :advertised-binding [M-S-left])
     (put 'outline-demote :advertised-binding [M-S-right])
     (put 'outline-move-subtree-up :advertised-binding [M-S-up])
     (put 'outline-move-subtree-down :advertised-binding [M-S-down])
     (put 'outshine-outline-hide-more :advertised-binding [M-left])
     (put 'outshine-outline-show-more :advertised-binding [M-right])
     (put 'outline-next-visible-header :advertised-binding [M-down])
     (put 'outline-previous-visible-header :advertised-binding [M-up])
     (put 'show-all :advertised-binding [?\M-# \?M-a])
     (put 'outline-up-heading :advertised-binding [?\M-# ?\M-u])
     (put 'outorg-edit-as-org :advertised-binding [?\M-# ?\M-#])

     ```
 3. I don't really know what that does, but it's just:

    ```elisp
    (with-eval-after-load 'eldoc
      (eldoc-add-command 'outshine-self-insert-command))
    ```
