### ISSUE TITLE
outshine-lang.el

### ISSUE THREAD

**Issue by bhyde** [alphapapa/outshine#2]
I was happy to find and use outshine-lang 

> ```
> ...
> ;; This code extends Thorsten Jolitz's excellent outshine mode ( http://orgmode.org/worg/org-tutorials/org-outside-org.html
> ;; ) to allow folding of language elements: classes, functions, and other language constructs.  Language elements are
> ;; matched by user-specified regexps (see customization `outshine-lang-headline-regexps').  The outline levels of all
> ;; language element headlines are made to be greater than the levels of any standard outshine headlines, so that language
> ;; elements are always subordinate to outshine headlines.  The outline level of a language headline is taken to be a
> ;; large fixed constant (specified by customization `outshine-lang-max-standard-level') plus the amount of whitespace
> ;; preceding the language headline.  Since most code is pretty-printed in a hierarchical way (and Python is required to be),
> ;; this heuristic usually works well enough.
> ...
> ```

I suspect it's visitigal that the link calls it outshine-python:  https://personal.broadinstitute.org/ilya/outshine-python.el

**Comment by alphapapa** [comment]
Hi Ben,

Thanks for sharing that, that's very cool.  How did you find it?

It would be interesting to add that to Outshine, but there are a few issues:

1.  That file has no license attached, so I don't think it would be good to include its code directly.  Of course, its functionality could be reimplemented, but that raises another issue...
2.  Does it make sense to add this when there are so many other ways of folding language-level elements in Emacs, like origami, hideshow, yafolding, folding, fold-this...the list is quite extensive.  :)

Do you know if using this provides any benefits compared to, say, hideshow, yafolding, or origami, which I think are the most popular folding packages for Emacs?

Thanks.

**Comment by bhyde** [comment]
On June 27, 2017 4:24:42 AM EDT, alphapapa <notifications@github.com> wrote:
>Hi Ben,
>
>Thanks for sharing that, that's very cool.  How did you find it?

I googled: outshine python 

>It would be interesting to add that to Outshine, but there are a few
>issues:
>
>1.  That file has no license attached, so I don't think it would be
>good to include its code directly.  Of course, its functionality could
>be reimplemented, but that raises another issue...

Right, maybe the author will notice the email I sent him.

>2.  Does it make sense to add this when there are so many other ways of
>folding language-level elements in Emacs, like origami, hideshow,
>yafolding, folding, fold-this...the list is quite extensive.  :)
>
>Do you know if using this provides any benefits compared to, say,
>hideshow, yafolding, or origami, which I think are the most popular
>folding packages for Emacs?

Is that not the eternal problem with emacs :)?  

I guess I should try all those, too...  Where's the time?
>
>Thanks.

**Comment by alphapapa** [comment]
Cool, thanks.

By the way, have you tried `navi-mode` and `helm-navi`?  They provide some helpful, language-specific navigation features.

**Comment by alphapapa** [comment]
I'm going to close this now.  Feel free to reopen or add comments if you have more info.  Thanks.

**Comment by JohnLunzer** [comment]
The benefit of outshine-lang.el is that it unifies code folding with outlining. This may or may not be desirable as the outline based folding ignores syntax where as hideshow/origami/etc will fold based on syntax/code-blocks and not just headlines. You just have to be really careful about your outline. 

In my case, for Python it's proven well enough to define `@`, `def` and `class` headlines in outshine-lang. 

Given the wide variety of code folding methods I would agree that it could be dubious to add code folding by default to outshine. 

My dream would be if syntax based folding could be cleanly merged with outline based folding. To my knowledge nothing like that exists at the moment.

**Comment by alphapapa** [comment]
> My dream would be if syntax based folding could be cleanly merged with outline based folding. To my knowledge nothing like that exists at the moment.

IIUC you can already do this by, e.g. using outline-minor-mode for commented-outline-based folding, and origami, et al. for syntax-based folding.
