### ISSUE TITLE
Simplify the outshine-outline prefix

### ISSUE THREAD

**Issue by thblt** [alphapapa/outshine#21]
Someone wrote the following on the discussion of #17 before apparently removing it:

---------------

Speaking of naming suggestions, what about shortening the currently named `outshine-outline-*` functions and variables to simply `outshine-*`? As far as I can tell, this only serves to document which symbols used to override the outline 'namespace'.

Aside from being slightly redundant, it results in some API inconsistency, eg. between `outshine-outline-cycle` and `outshine-cycle-buffer`, or `outline-next-heading` / `outshine-next-link` / `outshine-outline-next-line`

As  a quick reference here are the mentioned symbols:
```
Functions:
(interactive)
    outshine-outline-subheadings-visible-p
    outshine-outline-cycle
    outshine-outline-hide-more
    outshine-outline-next-line
    outshine-outline-show-more

(Non-interactive)
    outshine-outline-body-visible-p
    outshine-outline-subheadings-p
    outshine-outline-change-heading
    outshine-outline-cycle-emulate-tab
    outshine-outline-headings-list
    outshine-outline-cleanup-match
    outshine-outline-change-level
    outshine-outline-body-p
    outshine-outline-headings-atom
    outshine-outline-static-level-p

Variables:
    outshine-outline-cycle-emulate-tab
    outshine-outline-promotion-headings
    outshine-outline-regexp-base
    outshine-outline-regexp-outcommented-p
    outshine-outline-regexp-special-chars
```

---------

My feeling is these prefixes should stay, because these values are part of the outshine package (and thus belong in the `outshine-` pseudo-namespace but they don't require that outshine be actually enabled.

**Comment by alphapapa** [comment]
> My feeling is these prefixes should stay, because these values are part of the outshine package (and thus belong in the outshine- pseudo-namespace but they don't require that outshine be actually enabled.

I'm a bit confused.  I thought the suggestion was to change the symbol prefixes from `outshine-outline-` to `outshine-`, but this quote sounds like it's about an idea to change the prefixes to `outline-` (which of course we won't do).
