### ISSUE TITLE
Wrong hint in README.org

### ISSUE THREAD

**Issue by andreas-roehler** [alphapapa/outshine#23]
README.org says: 

"Outorg depends on Outshine"

Whilst outshine.el states:

;; Note that since version 2.0, outshine.el depends on outorg.el and
;; navi-mode.el depends on both, outshine.el and outorg.el. So the order
;; of installation should be

;;  1. outorg
;;  2. outshine
;;  3. navi-mode (optional)

**Comment by alphapapa** [comment]
> README.org says:
> 
> "Outorg depends on Outshine"

I don't see that anywhere in the readme.

**Comment by andreas-roehler** [comment]
Please read: README.org of Outorg says:... Sorry for the confusion. It's that circular dependency.
