### ISSUE TITLE
Can outshine mode support links like org-mode ? 

### ISSUE THREAD

**Issue by shankarpdy** [alphapapa/outshine#24]
Does the outshine mode support link (within a file) or across files ?

**Comment by shankarpdy** [comment]
It does support.
Can you org-store-link to store it.
Use "outshine-insert-link" to insert the link.

Thanks.

**Comment by thblt** [comment]
@To1ne We could reopen this, of course, but I'm not sure I understand why Outshine should handle this.  I understand it could be a useful feature, but what's wrong with a specialized package?

**Comment by To1ne** [comment]
Yeah, you're right. I'll see if I can submit a PR add a reference to that package in the README...

**Comment by thblt** [comment]
Take care the README is generated from comments in outshine.el, do not modify it directly.
