### ISSUE TITLE
incremental search does not search within collapsed regions

### ISSUE THREAD

**Issue by notestaff** [alphapapa/outshine#27]
In org-mode, when doing incremental search (ctrl-s), strings inside collapsed outline regions are still found (and automatically un-colapsed).  This currently doesn't seem to happen in outshine; one has to fully uncollapse all regions to find all occurrences.

**Comment by yuhan0** [comment]
This works fine for me - when you run `M-x describe-char` with your cursor on the `...` at the end of a collapsed headline, do you see an "outline-isearch-open-invisible" overlay property?

**Comment by thblt** [comment]
@notestaff Feel free to reopen if the issue is still present and you have more info.
