### ISSUE TITLE
ocaml / multiline comments

### ISSUE THREAD

**Issue by sapristi** [alphapapa/outshine#4]
Hello, 
thanks for maintaining this awesome program. I am using oushine with OCaml, and ran into some non-serious issues regarding the comment formatting done by outshine.

The ocaml comment syntax is a multiline block delimited by (* and *).
When making a multiline outshine comment, every line will be commented out, is there a way to bypass this ?

that is, instead of generating 
(* line 1 *)
(* line 2 *)
(* line 3 *), 
generate 
(* line 1
    line 2
    line 3 *)

Thanks again,

**Comment by alphapapa** [comment]
Hi,

Thanks for your kind words, but frankly I've done very little since I started maintaining it.  The original author, Thorsten, deserves all the credit.

I'm afraid I have no experience with OCaml, and I don't quite understand the problem.  Can you please give me a full example in source code blocks?

Specifically, I don't know what you mean by a "multiline outshine comment" or by "generating".  Are you by any chance using `outorg` as well?

**Comment by sapristi** [comment]
I guess I'm using outorg, since I edit the org parts in a buffer called outorg-edit-buffer.
Here is how I use the modes : 

1. I start by typing something like `(* * headline *)` in my source code
2. I then use the `M-# # `shortcut to edit in org-mode (in the outorg-edit-buffer), and I type to get the following :
```
* headline
line1
line2
```
3. I then use `M-#` to save the changes and go back to my source file. What I have then there is 
```
(* * headline *)
(* line1 *)
(* line2 *)
```
that is, each line is commented on it's own

4. Note that commenting the region with `M-x comment region`  (with `comment-style` set to `multi-line`)
```
(* * headline
 * line 1
 * line 2 *)
```
that is, there is one comment block, and other lines of the comment are made to start with ` *`



From what I understand, outline is supposed to use the `comment-region`, but that doesn't seem to be the case here.

**Comment by alphapapa** [comment]
Well, there's a note in the outorg readme about this:

> Outorg started out purely line-based, it only worked with one-line comments, i.e. with comment-sections like those produced by comment-region (a command that comments or uncomments each line in the region). It was enhanced later on to recognize comment regions too, i.e. those special multi-line comments found in many programming languages. But using outorg on such multi-line comments will probably change their syntax back to single-line whenever comment-region uses this style.

As far as I understand, outorg operates on line-based comments, not region-based ones.  I don't think there's any way to change that without major work to support region-based comments.

Is there any buggy behavior, or is it just a matter of the improved appearance that region-based comments would have?  Does OCaml not have line-based comments too?

**Comment by sapristi** [comment]
No there's no bug, it's only for convenience. But from what I understand of the note, outorg somehow depends on comment-region and so acts accordingly to the defined comment-style, which doesn't seem to be the case.

**Comment by sapristi** [comment]
Ok after playing some more with the outshine/outline it seems that multiline comments are indeed unsupported, since a multiline comment in the source file is recognised as such by outline (the first line is recognised as a comment, and following ones are inte

**Comment by sapristi** [comment]
Anyway thanks for your attention, it doesn't seem like the issue can be fixed by an easy hack...

**Comment by alphapapa** [comment]
Yeah, I think this is just a limitation that we'll have to deal with.  Patches welcome, of course, but personally I'm not interested in rewriting all that code to handle this situation.  :)  Thanks for bringing it up though, good to be aware of it.
