### ISSUE TITLE
Is there a better way to have multiple bindings on tab?

### ISSUE THREAD

**Issue by thblt** [alphapapa/outshine#41]
If outshine-cycle decides it cannot do anything, it runs a test which, if successful, calls `(indent-relative)`, which is, roughly, a hardcoded fallback ([here](https://github.com/alphapapa/outshine/blob/3e2aa4429789e33144b55214898540a6afec167d/outshine.el#L1982-L1984)).  Is there a way in Emacs to handle the case where a function bound to a key decides it doesn't want to do anything so Emacs can run the next function bound to the same key?

**Comment by thblt** [comment]
There's this:

https://stackoverflow.com/questions/2494096/emacs-key-binding-fallback

The issue is that we need to deactivate Outshine without losing state. `(setq outshine-mode nil)` seems to do exactly this: Emacs doesn't lookup keystrokes in `outshine-mode-map`, but `outshine--minor-mode-deactivate` doesn't run.

**Comment by alphapapa** [comment]
I don't know if we could or should use this in Outshine, but `general` seems to have support for this: https://github.com/noctuid/general.el/#predicates

**Comment by thblt** [comment]
@yuhan0 You're right, the problem is that there's a bug in CONDITION in the `define-key-with-fallback` binding for `outshine-cycle`: it doesn't handle the `C-u TAB` outside of an heading case.  I think if the condition is propertly written, we could totally remove the fallback branch in the function definition.
