### ISSUE TITLE
Outshine mode seems to break org todo note logging

### ISSUE THREAD

**Issue by MartinBuchmann** [alphapapa/outshine#45]
I tried to install outshine mode using the following in my init.el

```
(use-package outshine
    :ensure t
    :init
    (defvar outline-minor-mode-prefix "\M-#")
    :config
    (setq outshine-use-speed-commands t)
    :hook
    ((emacs-lisp-mode lisp-mode) . outshine-mode))
```

Everything is loaded without any issues but if I try to use org-capture as before `C-c C-c` doesn't shows any reaction, i.e. the capture buffer is kept open without being filed.

If I disable outshine mode again everything if fine. Is there any way to understand what's happening?

**Comment by thblt** [comment]
Could you give steps to reproduce from a minimal config please?

**Comment by MartinBuchmann** [comment]
Hmm, I am really sorry but I spent quite some time to check where the issue could be. I would have said that I have nothing special in my config but there must be something that I am missing. 

If no one else has experienced this problem, I would suggest to close the issue. I will notice you if i find something in the future.

**Comment by ilohmar** [comment]
I have an issue that seems somehow related: With my `outshine-mode` config, automatic logging of timestamps for repeating items breaks --- instead one is put into a buffer for a logging *note*, which is in `fundamental-mode`.  If I do not configure or load `outshine-mode` (but set the `outline-minor-mode-prefix`), all works well...

**Comment by ilohmar** [comment]
Ok, the problem occures if I've added `outshine-mode` to `prog-mode-hook` --- could that be the case for you as well?

**Comment by MartinBuchmann** [comment]
It is indeed very similar to my problem, thanks!

In my set-up the buffer for logging note is in org-mode. `outshine-mode` is not added to my `prog-mode-hook`, only to `emacs-lisp-mode-hook` and `lisp-mode-hook`. 

I really don't get it why 

a.) `outline-minor-mode-prefix` cannot be changed and 
b.) `org-ctrl-c-ctrl-c` does not work anymore when logging toto changes

**Comment by MartinBuchmann** [comment]
It is indeed very similar to my problem, thanks!

In my set-up the buffer for logging note is in org-mode. `outshine-mode` is not added to my `prog-mode-hook`, only to `emacs-lisp-mode-hook` and `lisp-mode-hook`. 

I really don't get it why 

a.) `outline-minor-mode-prefix` cannot be changed and 
b.) `org-ctrl-c-ctrl-c` does not work anymore when logging ToDo changes

**Comment by MartinBuchmann** [comment]
For the first issue described above I could track it down to a problem with org-ac. 

If I invoke Emacs using `emacs -Q -l ~/Desktop/org-ac-issue.el` `outline-minor-mode-prefix` is already defined and therefore not changed to the new key binding. If I change the order of the packages, i.e. first outshine than org-ac it works as expected! 

You can the file `org-ac-issue.el` in my gist

https://gist.github.com/MartinBuchmann/1959bd77d2718b119d8d7f6c35981f9b

**Comment by alphapapa** [comment]
I don't see `outline-minor-mode-prefix` in https://github.com/aki2o/org-ac/blob/master/org-ac.el.  You might want to look in the features it `require`s.

**Comment by MartinBuchmann** [comment]
> I don't see `outline-minor-mode-prefix` in https://github.com/aki2o/org-ac/blob/master/org-ac.el. You might want to look in the features it `require`s.

Hmm, I tried to do this but there is nothing which requires outline-mode or something similar. I have no idea what's wrong. With the change of the order it works for me at least.

**Comment by MartinBuchmann** [comment]
> Could you give steps to reproduce from a minimal config please?

I finally could condense it down to the following config which shows my problem:

https://gist.github.com/MartinBuchmann/241fcf3b3f8a3df93f37340ede32391d

1. Load this file as your init.el file
2. Visit an elisp or lisp file (before everything is working)
3. Visit an org file with a todo item
4. Change the todo state of the item via `C-c C-t`
5. The note buffer is opened but does not accept `C-c C-c` to finish the logging.

I am able to investigate this further, I am sorry.

**Comment by dzop** [comment]
I believe the issue is that `outshine--minor-mode-activate` advises `org-store-log-note` using around advise but will only call the original function if `outshine-mode` is enabled. This means that when inside an `org-mode` buffer, `org-store-log-note` has no effect.

You can quickly verify that changing the todo state works again by evaluating the following

```
(ad-deactivate 'org-store-log-note)
```

It looks like the intention is to advise `org-store-log-note` locally in the `outshine-mode` buffer. This can't be done using `defadvice` since it will add the advise globally to the function value of the `org-store-log-note` symbol. So really the advise should be added at the top level instead of inside `outshine--minor-mode-activate`.

You could then modify the body of the advise to something like

```emacs-lisp
(let (outshine-log-note-beg-marker
        outshine-log-note-end-marker)
    (when outshine-mode
      (setq outshine-log-note-beg-marker
            ;; stay before inserted text
            (copy-marker (outshine-mimic-org-log-note-marker) nil)
            outshine-log-note-end-marker
            ;; stay after inserted text
            (copy-marker (outshine-mimic-org-log-note-marker) t)))
    ad-do-it
    (when outshine-mode
      (unless (derived-mode-p 'org-mode 'org-agenda-mode)
        (outshine-comment-region outshine-log-note-beg-marker
                                 outshine-log-note-end-marker))
      (move-marker outshine-log-note-beg-marker nil)
      (move-marker outshine-log-note-end-marker nil)))
```

so that `org-store-log-note` works as intended in an `org-mode` buffer.

**Comment by MartinBuchmann** [comment]
`(ad-deactivate 'org-store-log-note)` indeed seems to bring back `org-store-log-note` back to work. I could only test it quickly but after evaluating it, I was able to use `C-c C-c` in the `Org note` buffer as before. Great!

**Comment by boothead** [comment]
I found something similar in spacemacs (see link above for details)

**Comment by yuhan0** [comment]
It seems that the `(when outshine-mode ...` condition was only added in the recent minor mode refactoring by @thblt:  <https://github.com/alphapapa/outshine/pull/19/commits/5d745bd944623be71de919b1463fd92f1468a4f2>  

Removing that clause also solves the issue:  

```emacs-lisp
(defadvice org-store-log-note (around org-store-log-note-around activate)
  "Outcomment inserted log-note in Outshine buffers."
  (let ((outshine-log-note-beg-marker
          ;; stay before inserted text
          ;; (copy-marker org-log-note-marker nil))
          (copy-marker (outshine-mimic-org-log-note-marker) nil))
        (outshine-log-note-end-marker
          ;; stay after inserted text
          ;; (copy-marker org-log-note-marker t)))
          (copy-marker (outshine-mimic-org-log-note-marker) t)))
    ad-do-it
    (unless (derived-mode-p 'org-mode 'org-agenda-mode)
      (outshine-comment-region outshine-log-note-beg-marker
                                outshine-log-note-end-marker))
    (move-marker outshine-log-note-beg-marker nil)
    (move-marker outshine-log-note-end-marker nil)))
```

The real question is, why does outshine even advise this function in the first place?? I don't see why `org-store-log-note` would be called in a non-org buffer, shouldn't there be an outshine wrapper around it using `outshine-use-outorg`?  

(disclaimer, I don't use any of the org-calling functionality besides `outshine-todo`)

**Comment by yuhan0** [comment]
Okay, so it appears that the `org-note` mechanism is used for `outshine-todo` when one's Org todo keywords have the `(@/!)` specification. This looks like quite a serious regression bug from the recent 3.0 update, @alphapapa do you mind if I open another hotfix PR for it?

**Comment by alphapapa** [comment]
@MartinBuchmann Thanks for the report and reproduction steps.

@dzop Thanks, your analysis seems correct.

@yuhan0 I guess Outshine advises the function so it can work in a code buffer that's using Outshine.  I think you're right that it should use `outshine-use-outorg` if possible.

In general, we should avoid advising functions globally, and if we do, it should be done when the minor mode is activated, and it should be removed when the mode is deactivated.

@yuhan0 Yes, I think we should patch this quickly, since it seems to be affecting people who may not even be aware that Outshine is loaded.  (I looked at those other bug reports, but I can't tell if Spacemacs is using Outshine by default.)  I'll go ahead and remove the conditional and release it as `3.0.1`, and then we can talk about how to solve the bigger problem.

@thblt What do you think?

Thanks to all.

**Comment by yuhan0** [comment]
Thanks for the quick fix! Spacemacs doesn't use outshine by default, but it can be added as an additional package in the regular manner.

**Comment by thblt** [comment]
Thanks all of you for fixing this, and sorry for introducing bugs :-)  Just a remark:

``` elisp
;; deactivate outshine:

  (advice-remove #'org-store-log-note #'outshine--around-org-store-log-note)
``` 

If the idea is to remove the advice when deactivating Outshine, I don't think it can work, since `outshine--deactivate` works on the active buffer, but the advice is global.
