### ISSUE TITLE
moving subtree up/down wont work when on headline after last update 

### ISSUE THREAD

**Issue by gbdu** [alphapapa/outshine#48]
just as title says, when the cursor is on an outshine headline, M-S-up won't move up and will see "Wrong type argument: number-or-marker-p, nil" in the messages. The subtree moves up fine when not on the headline

**Comment by alphapapa** [comment]
@yuhan0 Would you happen to have the time and interest to look into this?  Since you've been looking at the code a lot lately, you may be more familiar with it than I am.  If not, no problem.

**Comment by yuhan0** [comment]
I was unable to reproduce this - @gbdu could you post the full stacktrace? (toggle `M-x debug-on-error` before triggering the error)

Does it work if you call `M-x outline-move-subtree-up` instead of using the keybinding?
