### ISSUE TITLE
`outshine-cycle` doesn't work at all

### ISSUE THREAD

**Issue by mrbig033** [alphapapa/outshine#60]
#### Runtime Environment

- MX Linux 18
- GNU Emacs 27.0.50
- [~/.emacs.d](https://github.com/mrbig033/emacs)
- outshine 20190313.1153

#### Issue
The only thing it does is fold. After that it has no effect: the heading stays folded. Tested with `python-mode`, `godot-gdscript-mode` and also with/without Evil mode or any of my hooks.

**Comment by thblt** [comment]
Can you reproduce from `emacs -q`?

**Comment by yuhan0** [comment]
Does it work in any other modes? Outshine is currently incompatible with python-mode, see #42.

**Comment by mrbig033** [comment]
@thblt how can I reproduce this with `emacs -q` is it doesn't load my init?

**Comment by yuhan0** [comment]
Yeah it's probably the same issue as #42, looks like godot-gdscript-mode also sets the `outline-heading-end-regexp`: https://github.com/francogarcia/godot-gdscript.el/blob/master/godot-gdscript.el#L3961

**Comment by mrbig033** [comment]
Since I'm only interested in these two languages, I won't test it further, then. Maybe next time.

**Comment by yuhan0** [comment]
For a quick fix you could append the following to the function `outshine-set-local-outline-regexp-and-level`:
```elisp
(setq-local outline-heading-end-regexp "\n")
```

**Comment by thblt** [comment]
@mrbig033 As a general rule, to file bugs against Emacs packages it is recommended to provide steps to reproduce the issue from `-q` or `-Q`.  This makes maintainers' job a let easier and thus your bugs much more likely to be solved.

**Comment by mrbig033** [comment]
@thblt that is fair. But what I don't understand is how to load my init, which contains the package I wish to test, when the `-q` option means `--no-init-file`. I wasn't saying you were wrong, I was stating my ignorance.

**Comment by thblt** [comment]
The idea is to avoid loading your init. Instead, you could do something like this:

``` elisp
(add-to-list 'load-path "/absolute/path/to/outshine/package/directory")
(require 'outshine)
```

Notice the path needs to be absolute, eg `~` won't work.

**Comment by thblt** [comment]
Or actually just 

``` elisp
(require 'package)
(package-initialize)
```
