### ISSUE TITLE
Display images

### ISSUE THREAD

**Issue by 11111000000** [alphapapa/outshine#61]
To display images inserted like that: `;; [[./test.gif]]`

**Comment by thblt** [comment]
Have you looked into `iimage-mode`?

This is an interesting feature, but I don't think it belongs in Outshine.

**Comment by 11111000000** [comment]
![2019-04-12-001152_1366x768_scrot](https://user-images.githubusercontent.com/977130/55973235-b495d680-5cb7-11e9-90e4-ce68c4ecefd5.png)

@thblt it works great, thanks!
