### ISSUE TITLE
fixed pitch for code, but variable pitch for comments?

### ISSUE THREAD

**Issue by 11111000000** [alphapapa/outshine#62]
how to achieve fixed pitch for code, but variable pitch for comments? (in `mixed-pitch-mode` or `variable-pitch-mode`, like I do for org-mode (left)

![2019-04-12-002752_1366x768_scrot](https://user-images.githubusercontent.com/977130/55974248-da23df80-5cb9-11e9-86f7-d761622aa652.png)

now, when `variable-pitch-mode`  turned on, all text in right buffler are variable pitched, but I want for only comments are.

**Comment by thblt** [comment]
What about using `face-remap-add-relative` to make the comment face inherit from variable-pitch in the current buffer?
