### ISSUE TITLE
outshine hook and outline-regexp (bookmark.el)

### ISSUE THREAD

**Issue by ouboub** [alphapapa/outshine#66]
Hi
I am using the latest outorg and outshine versiona availble via the package system. I am not sure whether it is an outorg or outhine problem:

I am a long term user of bookmark.el.
My standard setting is the following

 (add-hook 'bookmark-bmenu-mode-hook 'hide-body)
 (add-hook 'bookmark-bmenu-mode-hook 'turn-on-outline-minor-mode)
 (add-hook 'bookmark-bmenu-mode-hook 'my-set-outline-bookmark)

(defun my-set-outline-bookmark ()
  (interactive)
  (set-variable 'outline-regexp "  [A-Z,0-9,\-]*:1.1")
  (message "Now the outline-regexp is set to \"  [A-Z]*:1.1\" "))

Now recently I started to use outshine mode, because I use outorg.el
By using these two package 
the outline-minor-mode-hook contains the  
outshine-hook-function
then when running bookmark-bmenu-list I obtain 
 Now the outline-regexp is set to "  [A-Z]*:1.1" 
Cannot calculate outcommented outline-regexp
without ’comment-start’ character defined!
So the kludge was 
(defun my-set-outline-bookmark ()
  (interactive)
  (set-variable 'outline-regexp "  [A-Z,0-9,\-]*:1.1")
  (remove-hook 'outline-minor-mode-hook 'outshine-hook-function)
  (message "Now the outline-regexp is set to \"  [A-Z]*:1.1\" "))

And then once I finish with bookmark to add the hook again.
because otherwise outorg wouldn't work
However this annoying. Do you have any suggestion or is the problem?

Regards

Uwe Brauer

**Comment by alphapapa** [comment]
Hi,

Sorry, I don't understand the problem you're having.  As I said, the package has changed recently.  Please check the installation and usage instructions in the readme, because I think you haven't seen the new ones yet.  

Also, ensure you are *actually* using the latest version.  For example, you should not be using `outshine-hook-function`:

```el
(defun outshine-hook-function ()
  "DEPRECATED, use `outshine-mode'."
  (warn "`outshine-hook-function' has been deprecated, use `outshine-mode'")
  (outshine-mode 1))
```

I've never used `bookmark-bmenu-mode`, so I've no idea if it is compatible with `outline-minor-mode` or `outshine`.

**Comment by ouboub** [comment]
Well I installed the latest version available via the package system, which comes as 
outshine-20190313.1153. It would be good if the package system provides the latest version.

bookmark.el is very old and it is compatible with outline-minor-mode, it seems however not compatible 
if the the outline-minor-mode-hook contains the outshine-hook-function or the outshine-function.
It seems that this function when added to the outline-minor-mode-hook makes bookmark incompatible with outline-minor-hook.

**Comment by alphapapa** [comment]
> Well I installed the latest version available via the package system, which comes as outshine-20190313.1153. It would be good if the package system provides the latest version.

The latest version is on MELPA.  Note that MELPA is not "the package system," but a repository that the package system can use.

> bookmark.el is very old and it is compatible with outline-minor-mode, it seems however not compatible if the the outline-minor-mode-hook contains the outshine-hook-function or the outshine-function.  

bookmark.el is part of Emacs, yes.  

I just tried the `bookmark-bmenu-list` command, so I see what it is, but I don't see how `outline-minor-mode` would be helpful, because there are no outline headings.

> It seems that this function when added to the outline-minor-mode-hook makes bookmark incompatible with outline-minor-hook.

`outshine` and `outorg` are intended to be used in e.g. source code buffers which have commented outline headings.  That is not the case in the `bookmark-bmenu-list` buffer.

**Comment by ouboub** [comment]
outshine version, so I have the actual version installed, for me the package system contains all repos, 
GNU elpa, melpa and marmelade.

Bookmark:
when you have a lot of bookmarks (as I do), the following setting is very helpful
  (set-variable 'outline-regexp "  [A-Z,0-9,\-]*:1.1")
Then my bookmark file looks like
BIB:1.1..

when turning outline-minor-mode off 
it looks like

  BIB:1.1 Main(file)
 *BIB:1.2  Hale_interview
 *BIB:1.2  Moore, Statistics LabEst
  BIB:1.2. Payne
  BIB:1.2. marsden
  BIB:1.2. marsden79
  BIB:1.2. ratiu
  Beihilfe-Debeka

which is really helpful, however when the outshine function is in the outline-minor-hook
the syntax   (set-variable 'outline-regexp "  [A-Z,0-9,\-]*:1.1")
is so to speak rejected and my bookmark buffer is NOT outlined.
how can this be avoided save using me kludge of removing and adding the outshine function to the outline minor hook

**Comment by alphapapa** [comment]
> outshine version, so I have the actual version installed

I don't understand what that means.

> Bookmark:
> when you have a lot of bookmarks (as I do), the following setting is very helpful
> (set-variable 'outline-regexp " [A-Z,0-9,-]*:1.1")
> Then my bookmark file looks like
> BIB:1.1..
> 
> when turning outline-minor-mode off
> it looks like
> 
> BIB:1.1 Main(file)
> *BIB:1.2 Hale_interview
> *BIB:1.2 Moore, Statistics LabEst
> BIB:1.2. Payne
> BIB:1.2. marsden
> BIB:1.2. marsden79
> BIB:1.2. ratiu
> Beihilfe-Debeka
> 
> which is really helpful

Thank you for the example.  Now I understand what you're doing.

> when the outshine function is in the outline-minor-hook
> the syntax (set-variable 'outline-regexp " [A-Z,0-9,-]*:1.1")
> is so to speak rejected and my bookmark buffer is NOT outlined.

As I said in the previous message, `outline-minor-mode` and, especially, `outshine` are not designed to be used in that way.  There are easier and more effective ways to get the effect you desire, i.e. visually distinguishing certain entries in `bookmark-bmenu-list` buffers.  Try `highlight-regexp`, for example.

But if you insist on trying to use `outline-minor-mode` for this effect, then you need not use `outshine` at all. 

> how can this be avoided save using me kludge of removing and adding the outshine function to the outline minor hook

If I may be blunt, you are doing it wrong.  As I said, please read the instructions in the `outshine` README file for how to properly use the current version of `outshine`.

**Comment by ouboub** [comment]
> I don't understand what that means.
But you are the author and you provide the package versus melpa, if you don't understand that, who else?

> But if you insist on trying to use outline-minor-mode for this effect, then you need not use outshine at all.

sigh, maybe some text was not transmitted, so let me try to say that again:

I am using outorg very very often, outorg depends on outshine. If I remove the outshine hook from the 
outline-minor-mode outorg does not work.

As said I used bookmarks for years, but it seems outshine breaks compatiblity with old outline regexp syntax and ask for a fix.

> If I may be blunt, you are doing it wrong. As I said, please read the instructions in the outshine README file for how to properly use the current version of outshine.

If I may be blunt, I don't understand what this comment has to do with 
> how can this be avoided save using me kludge of removing and adding the outshine function to the  outline minor hook

there is a package in melpa, but you insist that this is not the current version. well I would say, either remove it from MELPA, which would be a shame, since it is very convenient or try to upgrade the MELPA package.

to come back to my original question:
how can I use outorg (and therefore outshine) and old trusted outline regexp syntax?

**Comment by alphapapa** [comment]
I don't understand why there is such a communication problem here.

> > > outshine version, so I have the actual version installed,

> > I don't understand what that means.

> But you are the author and you provide the package versus melpa, if you don't understand that, who else?

Look at the words I quoted.  Those are the words I do not understand.  What does "I have the actual version installed" mean?  What does "the actual version" mean?

> there is a package in melpa, but you insist that this is not the current version

I have said nothing like that.  Are you reading the words I'm writing?

> > If I may be blunt, you are doing it wrong. As I said, please read the instructions in the outshine README file for how to properly use the current version of outshine.

> If I may be blunt, I don't understand what this comment has to do with

I cannot be any more clear than that without reiterating what is already written in the readme.  I've asked you twice to read the readme file and use the instructions for the current version of the package.  You have ignored that request and continue to repeat your question.

I will say this one more time:

**outline-minor-mode and, especially, outshine are not designed to be used in that way.  If you insist on trying to use outline-minor-mode for this effect, then you need not use outshine at all.  Just use `outline-minor-mode`.  Stop using hooks from obsolete versions of outshine.  Use the instructions for the current version of the package.**

**Comment by ouboub** [comment]
Ok, I did what you said and have a couple of remarks to make.
I cloned both outorg and outshine from github, I run a diff of both .el with the latest melpa version, they are identical. so far so good.
I followed the instructions in both README files
and tried to use outorg and  I run into a problem, I think it is connected to outshine, but i might be wrong and we should shift the discussion to the outorg repo.

be it as it may.

here is what i did in a gnus message buffer.
1.outorg-edit-as-org:
I obtained
outorg-edit-as-org: Activate ‘outline-minor-mode’ to use ‘outorg’
so i did this
(I did this in my previous setting but since I deleted all the setting, I do it now step by step)
so i run outline-minor-mode
and then I obtain (the well known) error
Before first heading 

and the outorg buffer is not usuable

**Comment by ouboub** [comment]
I meant after running outline-minor-mode
I run outorg-edit-as-org and I obtain
Before first heading

and the outorg buffer is not usuable

**Comment by ouboub** [comment]
sorry for my 
 outorg-edit-as-org
only works with 
(add-hook 'outline-minor-mode-hook 'outshine-mode)
so is this a bug, or misconfiguration on my part?

**Comment by alphapapa** [comment]
> here is what i did in a gnus message buffer.  after running outline-minor-mode I run outorg-edit-as-org and I obtain `Before first heading` and the outorg buffer is not usuable

As I said in an earlier message:

**`outshine` and `outorg` are intended to be used in e.g. source code buffers which have commented outline headings.**  I don't know why you would try to use them in a Gnus message buffer.  That is not the intended use of these packages, and that is not supported.

This is all explained in the documentation:

**Outorg is for editing comment-sections of source-code files in temporary Org-mode buffers.**

**An outshine buffer is structured like an org-mode buffer, only with outcommented headlines.**

**Comment by ouboub** [comment]
Well to use outorg in a gnus message is very helpful if you want to use org-mime for sending (not to often)
html mail. For that purpose there is already orgtbl mode which just gives access to a subset of the org functionality.   You should give it a try......

In any case I finally found a solution to my problem I have to add the 
(add-hook 'message-mode-hook  'my-add-outshine-hook)
and then either remove that hook when sending the mail or using bmenu. 
So you can close that issue.
Thanks
