### ISSUE TITLE
outshine-kbd-<backtab>: Wrong type argument: commandp, nil when pressing <backtab> outside the condition defined by outshine-define-key

### ISSUE THREAD

**Issue by cyrus-and** [alphapapa/outshine#73]
## The issue

`<backtab>` doesn't work when the point is not on headings or beginning of buffer.

## How to reproduce

1. Create and open the following `outshine-issue.el` file:

   ```
   ;;; Foo

   xxx

   ;; Local Variables:
   ;; eval: (outshine-mode)
   ;; End:
   ```

2. Move the point to the line where `xxx` is;

3. Press `<backtab>`.

At this point the error is triggered and the visibility is not cycled:

```
outshine-kbd-<backtab>: Wrong type argument: commandp, nil
```

## Versions

- Debian GNU/Linux 10
- GNU Emacs 26.1
- outshine version 20190717.1147 (from MELPA);

## Personal considerations and possible solution

`<backtab>` is bound with:

https://github.com/alphapapa/outshine/blob/4c6107da8fd6119ba1b2379cd2f68c8c7374e8d5/outshine.el#L2403-L2405

And it supposedly should cycle the buffer when the point is on a heading or at the beginning. If outshine tries to mimic the Org experience why do we need this condition? `<backtab>` in Org always cycles the buffer unless the point is on a table. I'd suggest to replace the above with:

```elisp
(outshine-define-key outshine-mode-map
  (kbd "<backtab>") 'outshine-cycle-buffer t)
```

Which incidentally also fixes the reported issue.

(Disclaimer: I'm not a Org user myself.)

**Comment by thblt** [comment]
Thanks for the detailed report, I can reproduce the issue.

>  If outshine tries to mimic the Org experience why do we need this condition?

Outshine is meant for code buffers, where tab/backtab are commonly used bindings.

**Comment by cyrus-and** [comment]
> Outshine is meant for code buffers, where tab/backtab are commonly used bindings.

`<backtab>` is undefined/useless in all the programming modes I know of, but I see your point. I can always rebind it without conditions in my `.emacs`.

**Comment by alphapapa** [comment]
I agree with @thblt that backtab shouldn't cycle outlines unless point is on a heading, by default.  I think it's common to use tab to indent and backtab to unindent.

However, I guess this shouldn't raise the wrong-type-argument error, right?

**Comment by cyrus-and** [comment]
> However, I guess this shouldn't raise the wrong-type-argument error, right?

Yep, the problem appears to be that `(key-binding (kbd "<backtab>"))` is `nil` in the resulting lambda function because there is no global binding for `<backtab>` in this case (`emacs-lisp-mode`):

https://github.com/alphapapa/outshine/blob/4c6107da8fd6119ba1b2379cd2f68c8c7374e8d5/outshine.el#L887-L895

IMHO is enough to just check whether there is an *original function* or not and skip the `call-interactively` in the latter case.

**Comment by thblt** [comment]
What about:

``` elisp
(or (key-binding ,key)
    (lambda nil (interactive) (message "%s does nothing useful here."  ,key)))
```

**Comment by thblt** [comment]
(cont.) So we don’t just do nothing. I don’t like the idea of an (interactive) function having no effect without explaining why. That’s what Org does with, eg, `C-c C-c`

**Comment by alphapapa** [comment]
> I don’t like the idea of an (interactive) function having no effect without explaining why. That’s what Org does with, eg, `C-c C-c`

Yes, I agree.  For this key binding in particular, we might consider a message something like: "Point not on heading and key is not otherwise bound here", although that might read awkwardly for end-users.

**Comment by thblt** [comment]
>  For this key binding in particular, we might consider a message something like

That would require adding a second &optional argument to `outshine-define-key`, is it really worth it?

**Comment by thblt** [comment]
Notice the docstring of the generated functions is very clear, confused users can use `view-lossage` to determine what happened:

``` 
outshine-kbd-<backtab> is an interactive Lisp function in
‘outshine.el’.

(outshine-kbd-<backtab>)

Run the interactive command ‘outshine-cycle-buffer’ if the following condition is satisfied:

    (or (outline-on-heading-p) (bobp))

Otherwise, fallback to the original binding of (kbd <backtab>) in the current mode.

[back]
```

**Comment by alphapapa** [comment]
Sounds good.  Thanks.
