### ISSUE TITLE
org-bullets-mode analogue

### ISSUE THREAD

**Issue by 11111000000** [alphapapa/outshine#88]
replace **** with one glyph

**Comment by 11111000000** [comment]
I create outshine-bullets-mode, based on org-bullets-mode, I think it's look nice!

 but it works now only for emacs-lisp style comments and `;;;` style headings, but not for `;; *`.

**Comment by 11111000000** [comment]
https://github.com/11111000000/outshine-bullets

**Comment by alphapapa** [comment]
If you want bullets in outline-like buffers other than `org-mode` buffers, you should probably look at enhancing `org-superstar` to work with `outline-minor-mode` buffers.  At least, your work should be based on it, because it supersedes org-bullets.
