### ISSUE TITLE
Syntax error in font option pcase

### ISSUE THREAD

**Issue by SpiderPig** [alphapapa/outshine#9]
https://github.com/alphapapa/outshine/blob/75389b7104692f4f6a97dc72020d145f03affd25/outshine.el#L1614

pcase expects backquotes for the pattern. so.
(\`t t)
(\`nil nil)
Not
('t t)

**Comment by alphapapa** [comment]
No, it works fine.

**Comment by SpiderPig** [comment]
Yea, I was asking about this on #emacs on irc.  One person reported it working.  But even with a raw version of emacs I get an error if I evaluate (pcase x ('t t)).  From what I learned though the backquote causes it to be understood as a Q-pattern while the regular quote gets taken as a U-pattern.  According to the manual the pattern atom is self quoting. So this should work even with out the quote for t and nil.   For some reason emacs (for me at least) may be self quoting the quoted atom perhaps?
''''
Debugger entered--Lisp error: (error "Unknown upattern `(quote t)'")
  signal(error ("Unknown upattern `(quote t)'"))
''''
I've tried that on emacs 25.3 and 24.5 on two different distros. One of which I downloaded and compiled myself.  I have no idea what could be causing this different behaviour.

**Comment by alphapapa** [comment]
As far as I can tell, it only works correctly as it is:

```el
(let ((outshine-fontify t))
  (pcase outshine-fontify
    ('t t)
    ('nil nil)
    ((pred functionp) (funcall outshine-fontify))
    (_ (user-error "Invalid value for variable `outshine-fontify'"))))  ; => t

(let ((outshine-fontify nil))
  (pcase outshine-fontify
    ('t t)
    ('nil nil)
    ((pred functionp) (funcall outshine-fontify))
    (_ (user-error "Invalid value for variable `outshine-fontify'")))) ; => nil

(let ((outshine-fontify 1))
  (pcase outshine-fontify
    ('t t)
    ('nil nil)
    ((pred functionp) (funcall outshine-fontify))
    (_ (user-error "Invalid value for variable `outshine-fontify'"))))  ; => "Error: Invalid value..."

;; Unquoted patterns:

(let ((outshine-fontify 1))
  (pcase outshine-fontify
    (t t)
    ('nil nil)
    ((pred functionp) (funcall outshine-fontify))
    (_ (user-error "Invalid value for variable `outshine-fontify'")))) ; => t [should be "Error: ..."]

(let ((outshine-fontify nil))
  (pcase outshine-fontify
    ('t t)
    (nil nil)
    ((pred functionp) (funcall outshine-fontify))
    (_ (user-error "Invalid value for variable `outshine-fontify'"))))  ; => Debugger entered--Lisp error: (error "Unknown pattern ‘nil’")
```

I tested all of this when I was setting up the pcase and this is the only way it works correctly.  I can't explain why it would behave differently for you.

**Comment by SpiderPig** [comment]
Welp. It seems to have been some kind of issue from the update.  All of the installs of emacs 25 are working now.  I have one machine with the emacs 24 that I started with which still has the problem.  What ever it was must have been related to that.
thanks for the help. And for maintaining this!

**Comment by alphapapa** [comment]
No problem, I appreciate your trying to help.
