### ISSUE TITLE
Outline based LaTeX source code navigation.

### ISSUE THREAD

**Issue by hongyi-zhao** [alphapapa/outshine#95]
I'm not sure whether this package can help me to generate an outline based on the current master TeX source file to facilitate the source code navigation. Currently, I tried the following configuration, but I still cannot show the outline:

```elisp
(use-package outshine
  :demand t
  :init
  (defvar outline-minor-mode-prefix "\M-#")
  ;; https://github.com/alphapapa/outshine#activation
  :hook
  (LaTeX-mode . outshine-mode)
)
```
Any tips will be appreciated.

Regards,
Zhao

**Comment by alphapapa** [comment]
Hello,

Please see related issues, i.e. https://github.com/alphapapa/outshine/issues?q=is%3Aissue+latex

**Comment by hongyi-zhao** [comment]
I checked the above issue list, but still failed to find any clues.

**Comment by alphapapa** [comment]
Did you look at the issues in the list, or did you look at the list of issues?

**Comment by hongyi-zhao** [comment]
I found some configuration related code snippets here:

https://github.com/alphapapa/outshine/issues/63
https://github.com/alphapapa/outshine/issues/85
